# Generated by Django 5.1.4 on 2024-12-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='car_value',
            new_name='cars_value',
        ),
    ]
